# Site settings
title: Long's Blog
email: chenlong888@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Life worth memory
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.mycodes.me" # the base hostname & protocol for your site
twitter_username: tinnnyo
github_username:  54microlong

# Build settings
markdown: kramdown
